export const SITE_URL = 'https://www.getfintegrity.com'
export const BOOKING_URL = 'https://calendar.app.google/LFgyb9Bj2fe5VqJw8'
export const CONTACT_EMAIL = 'contact@getfintegrity.com'
export const LINKEDIN_URL = 'https://www.linkedin.com/company/getfintegrity/'
export const API_DOCS_URL = 'https://api.dev.getfintegrity.com/'
